/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates the Firebase account and the matching profile. Sign in with
         *     the Firebase client SDK afterwards to get an ID token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description User created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example user created */
                            message: string;
                            /** @description Firebase UID. */
                            user_id: string;
                            /**
                             * @description True when the user must verify their email before the API
                             *     accepts their token.
                             */
                            email_verification_required: boolean;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Email already registered, or username already taken (usernames are unique ignoring case, so `Alice` and `alice` conflict). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Too many registrations from this IP; see `Retry-After`. */
                429: {
                    headers: {
                        /** @description Seconds to wait before retrying. */
                        "Retry-After"?: number;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in user's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Missing or invalid token, or no profile exists for the token's user. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                403: components["responses"]["EmailNotVerified"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warbands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the signed-in user's warbands
         * @description Newest first, each with its units and computed totals.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The user's warbands (empty array if none). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Warband"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warbands/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a warband */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateWarbandRequest"];
                };
            };
            responses: {
                /** @description The new warband. Omitted optional fields default to empty or 0. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Warband"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                /** @description Limit reached (50 warbands per user). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warbands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Get a warband
         * @description Public. Includes its units and computed totals.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The warband. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Warband"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a warband
         * @description Also deletes its units and removes it from any campaigns. Owner only.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a warband
         * @description Only the fields you send are changed. Owner only.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateWarbandRequest"];
                };
            };
            responses: {
                /** @description The updated warband. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Warband"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/units/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a unit in one of your warbands */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUnitRequest"];
                };
            };
            responses: {
                /** @description The new unit. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
                /** @description Invalid body, or `warband_id` is not a valid UUID. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                /** @description The warband does not exist or is not yours. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Limit reached (100 units per warband). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Get a unit
         * @description Public.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The unit. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a unit
         * @description Only the owner of the unit's warband may do this.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a unit
         * @description Only the fields you send are changed. Only the owner of the unit's warband may do this.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUnitRequest"];
                };
            };
            responses: {
                /** @description The updated unit. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/units/{id}/kills": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Add to a unit's kills
         * @description The amount may be negative; the total never goes below 0. Owner only.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IncrementRequest"];
                };
            };
            responses: {
                /** @description The updated unit. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/units/{id}/xp": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Add to a unit's experience
         * @description The amount may be negative; the total never goes below 0. Owner only.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IncrementRequest"];
                };
            };
            responses: {
                /** @description The updated unit. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/units/{id}/perk": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Add a perk or scar to a unit
         * @description The server generates the perk's ID. Owner only.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddPerkRequest"];
                };
            };
            responses: {
                /** @description The updated unit, including the new perk. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                /** @description Limit reached (50 perks per unit). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/units/{id}/perk/{perkId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                perkId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a perk or scar from a unit
         * @description Owner only.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    perkId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The updated unit. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                /** @description The unit or perk does not exist, or the unit is not yours. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my campaigns
         * @description Campaigns the user owns or has a warband in, newest first, each with chapters, teams, and warbands.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The user's campaigns (empty array if none). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a campaign
         * @description The new campaign has no teams; the owner adds them before warbands can join.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCampaignRequest"];
                };
            };
            responses: {
                /** @description The new campaign. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                /** @description Limit reached (20 campaigns per user). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Get a campaign
         * @description Public. Anyone with the ID can view it; the ID is also what a player needs to join.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The campaign with its chapters, teams, and member warbands. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"];
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a campaign
         * @description Also deletes its chapters, teams, and memberships. The warbands themselves are kept. Campaign owner only.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a campaign
         * @description Only the fields you send are changed. Campaign owner only.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCampaignRequest"];
                };
            };
            responses: {
                /** @description The updated campaign. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/campaigns/{id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a chapter
         * @description Appended after the last chapter unless `sort_order` is given. Campaign owner only.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateChapterRequest"];
                };
            };
            responses: {
                /** @description The new chapter. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampaignChapter"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                /** @description Limit reached (100 chapters per campaign). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/chapters/{chapterId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                chapterId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a chapter
         * @description Campaign owner only.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    chapterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update or reorder a chapter
         * @description Only the fields you send are changed. Campaign owner only.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    chapterId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateChapterRequest"];
                };
            };
            responses: {
                /** @description The updated chapter. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampaignChapter"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/campaigns/{id}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a team
         * @description A campaign can have any number of teams. Names are unique within a campaign. Campaign owner only.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamRequest"];
                };
            };
            responses: {
                /** @description The new team. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampaignTeam"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                /** @description The campaign already has a team with that name, or already has 20 teams. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/teams/{teamId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                teamId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a team
         * @description Only teams with no warbands on them can be deleted. Campaign owner only.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    teamId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                /** @description Warbands are still on the team; move them first. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Rename a team
         * @description Campaign owner only.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    teamId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamRequest"];
                };
            };
            responses: {
                /** @description The renamed team. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampaignTeam"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                /** @description The campaign already has a team with that name. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
    "/campaigns/{id}/join-code": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Get the campaign's join code
         * @description Campaign owner only. Share it with the players you want to let in.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The join code. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JoinCodeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/join-code/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace the campaign's join code
         * @description Campaign owner only. The old code stops working immediately. Warbands
         *     that already joined stay in the campaign.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The new join code. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JoinCodeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/warbands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join a campaign with one of your warbands
         * @description Needs the campaign's join code (not just its public ID), unless you own
         *     the campaign. A warband can be in many campaigns but only once in each,
         *     on exactly one team. Limited to 10 attempts, then 1 per 6 seconds, per
         *     client IP.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JoinCampaignRequest"];
                };
            };
            responses: {
                /** @description The campaign, including the new membership. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"];
                    };
                };
                /** @description Invalid body, or `warband_id` or `team_id` is not a valid UUID. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /**
                 * @description The join code is missing or wrong (`join code required` or
                 *     `invalid join code`), or the email is not verified
                 *     (`email not verified`).
                 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description The campaign does not exist, the warband is not yours, or the team is not in this campaign. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description The warband is already in this campaign, or the campaign already has 100 warbands. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{id}/warbands/{warbandId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                warbandId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a warband from a campaign
         * @description Allowed for the campaign owner or the warband's owner. The warband itself is kept.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    warbandId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                /** @description The warband is not in this campaign, or you own neither the campaign nor the warband. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Move a warband to another team
         * @description Allowed for the campaign owner or the warband's owner.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    warbandId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeTeamRequest"];
                };
            };
            responses: {
                /** @description The campaign with the updated membership. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["EmailNotVerified"];
                /** @description The warband or team is not in this campaign, or you own neither the campaign nor the warband. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["ServerError"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        User: {
            /** @description Firebase UID. */
            id: string;
            /** Format: email */
            email: string;
            username: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Perk: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** @description Scars count against crusade points; perks count for them. */
            is_scar: boolean;
        };
        Unit: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            warband_id: string;
            unit_name: string;
            narrative_name: string;
            bio: string;
            points: number;
            kills: number;
            experience: number;
            perks: components["schemas"]["Perk"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Warband: {
            /** Format: uuid */
            id: string;
            /** @description Owner's Firebase UID. */
            user_id: string;
            name: string;
            faction: string;
            description: string;
            requisition_points: number;
            supply_limit: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            units: components["schemas"]["Unit"][];
            /** @description Number of units. */
            num_units: number;
            /** @description Sum of the units' points. */
            total_points_cost: number;
            /** @description One per perk and minus one per scar, across all units. */
            crusade_points: number;
        };
        CampaignSettings: {
            points_per_win: number;
            points_per_loss: number;
            starting_requisition: number;
        };
        CampaignChapter: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            campaign_id: string;
            title: string;
            description: string;
            /** @description Chapters are listed in ascending order. */
            sort_order: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CampaignTeam: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            campaign_id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description A warband's membership in a campaign. */
        CampaignWarband: {
            /** Format: uuid */
            campaign_id: string;
            /** Format: uuid */
            warband_id: string;
            warband_name: string;
            /** Format: uuid */
            team_id: string;
            /** Format: date-time */
            joined_at: string;
        };
        Campaign: {
            /** Format: uuid */
            id: string;
            /** @description Owner's Firebase UID. */
            owner_id: string;
            name: string;
            description: string;
            settings: components["schemas"]["CampaignSettings"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * @description The secret players need to join. Only present for the campaign's
             *     owner: in the response to creating a campaign and in the owner's
             *     `GET /campaigns`. Never in public responses.
             */
            join_code?: string;
            chapters: components["schemas"]["CampaignChapter"][];
            teams: components["schemas"]["CampaignTeam"][];
            warbands: components["schemas"]["CampaignWarband"][];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** @description Must be unique; not blank. */
            username: string;
            /**
             * Format: password
             * @description Also subject to Firebase's password rules.
             */
            password: string;
        };
        CreateWarbandRequest: {
            /** @description Not blank. */
            name: string;
            faction?: string;
            description?: string;
            requisition_points?: number;
            supply_limit?: number;
        };
        /** @description Send only the fields to change. */
        UpdateWarbandRequest: {
            /** @description Not blank. */
            name?: string;
            faction?: string;
            description?: string;
            requisition_points?: number;
            supply_limit?: number;
        };
        CreateUnitRequest: {
            /**
             * Format: uuid
             * @description A warband you own.
             */
            warband_id: string;
            /** @description Not blank. */
            unit_name: string;
            narrative_name?: string;
            bio?: string;
            points?: number;
        };
        /** @description Send only the fields to change. */
        UpdateUnitRequest: {
            /** @description Not blank. */
            unit_name?: string;
            narrative_name?: string;
            bio?: string;
            points?: number;
        };
        IncrementRequest: {
            /** @description Positive or negative. 0 is allowed and changes nothing. The field is required. */
            amount: number;
        };
        AddPerkRequest: {
            /** @description Not blank. */
            name: string;
            description?: string;
            /** @default false */
            is_scar: boolean;
        };
        CreateCampaignRequest: {
            /** @description Not blank. */
            name: string;
            description?: string;
            points_per_win?: number;
            points_per_loss?: number;
            starting_requisition?: number;
        };
        /** @description Send only the fields to change. */
        UpdateCampaignRequest: {
            /** @description Not blank. */
            name?: string;
            description?: string;
            points_per_win?: number;
            points_per_loss?: number;
            starting_requisition?: number;
        };
        CreateChapterRequest: {
            /** @description Not blank. */
            title: string;
            description?: string;
            /** @description Defaults to one after the last chapter. An explicit 0 is honoured. */
            sort_order?: number;
        };
        /** @description Send only the fields to change. */
        UpdateChapterRequest: {
            /** @description Not blank. */
            title?: string;
            description?: string;
            sort_order?: number;
        };
        TeamRequest: {
            /** @description Not blank. */
            name: string;
        };
        JoinCampaignRequest: {
            /**
             * Format: uuid
             * @description A warband you own.
             */
            warband_id: string;
            /**
             * Format: uuid
             * @description A team in this campaign.
             */
            team_id: string;
            /**
             * @description The campaign's join code, from its owner. Required unless you own
             *     the campaign. Case, spaces and hyphens are ignored.
             */
            join_code?: string;
        };
        JoinCodeResponse: {
            join_code: string;
        };
        ChangeTeamRequest: {
            /**
             * Format: uuid
             * @description A team in this campaign.
             */
            team_id: string;
        };
    };
    responses: {
        /**
         * @description The token is valid but the account's email is not verified yet. Ask the
         *     user to verify their email, then fetch a fresh ID token.
         */
        EmailNotVerified: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "email not verified"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request body is malformed or fails validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Missing, malformed, expired, or revoked token (error `token revoked`),
         *     or the account has been disabled (error `account disabled`). Sign in
         *     again to get a new token; a disabled account cannot.
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Not found. Also returned when the resource belongs to someone else, or
         *     when an ID in the URL is not a valid UUID.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. Details are logged server-side, not returned. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "internal server error"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
